In [1]:
# 语义分割Demo
# 安装使用方法：https://pixellib.readthedocs.io/en/latest/index.html

# python=3.8

# TensorFlow
# Windows：pip3 install tensorflow==2.2.0 (最新版的2.8可能会报错)
# macOS：conda install -c conda-forge tensorflow

# pip3 install imgaug
# pip3 install pixellib --upgrade

# conda install -c conda-forge jupyterlab

In [2]:
# 导入常见包
import cv2
import numpy as np
import matplotlib.pyplot as plt
plt.rcParams['figure.dpi'] = 200

In [3]:
# 读取图片
img = cv2.imread('./images/baby.jpg')
img_cvt =cv2.cvtColor(img,cv2.COLOR_BGR2RGB)

In [ ]:
# 显示
plt.imshow(img_cvt)

In [5]:
# 导入pixellib
import pixellib

In [6]:
# 导入语义分割
from pixellib.semantic import semantic_segmentation

In [7]:
# 实例化
segment = semantic_segmentation()

In [8]:
# 加载模型
segment.load_ade20k_model('./weights/deeplabv3_xception65_ade20k.h5')

In [9]:
# 分割
results,output = segment.segmentFrameAsAde20k(img,overlay=True)

In [10]:
output.shape

(1000, 667, 3)

In [ ]:
plt.imshow(cv2.cvtColor(output,cv2.COLOR_BGR2RGB))

In [12]:
results

{'class_ids': [13, 1, 8, 40, 17, 23],
 'class_names': ['person', 'wall', 'bed', 'cushion', 'mountain', 'painting'],
 'class_colors': [array([150,   5,  61]),
  array([120, 120, 120]),
  array([204,   5, 255]),
  array([255, 194,   7]),
  array([143, 255, 140]),
  array([255,   6,  51])],
 'masks': array([[False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        ...,
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False],
        [False, False, False, ..., False, False, False]]),
 'ratios': [47.19345674486804,
  33.69512921554252,
  19.04726447947214,
  0.051548753665689145,
  0.008591458944281526,
  0.004009347507331378]}